---
# Old EC2 Module Docs:
# https://docs.ansible.com/ansible/2.9/modules/ec2_module.html#ec2-module

- name: Provision instance in AWS
  hosts: localhost
  gather_facts: false
  vars:
    security_group_id: sg-0bdbd70e35827b5f9
    ami_id: ami-03debf3ebf61b20cd
    instance_size: m4.xlarge
    instance_tags: {"Name":"aap2-migration-demo-v2_9"}
    vpc_id: vpc-0c905f1fdf60945bd
    ssh_key_name: ansible-ssa-demo-key
    region: us-east-1
    subnet_id: subnet-0cd4ed414d34e70e5

  tasks:
  - name: Provision instance
    ec2:
      aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
      aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
      region: "{{ region }}"
      key_name: "{{ ssh_key_name }}"
      group_id: "{{ security_group_id }}"
      instance_type: "{{ instance_size }}"
      instance_tags: "{{ instance_tags }}"
      image: "{{ ami_id }}"
      wait: yes
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: yes
    register: ec2_instance_facts

  - name: copy ec2_instance_facts to localhost
    copy: 
      content: "{{ ec2_instance_facts | to_nice_yaml }}"
      dest: /var/tmp/ec2-facts.yml
