---
- name: Provision instance in AWS
  hosts: localhost
  gather_facts: false
  vars:
    security_group_id: sg-079ebd58a00104d74
    ami_id: ami-0251f146af87abba4
    instance_size: m4.xlarge
    instance_tags: {'Name':'mkb-platform-ec2-instance'}
    vpc_id: vpc-0c905f1fdf60945bd
    ssh_key_name: ansible-ssa-demo-key
    region: us-east-2
    subnet_id: subnet-0cd4ed414d34e70e5

  collections: 
    - amazon.aws

  tasks:
  - name: Provision instance
    amazon.aws.ec2_instance:
      region: "{{ region }}"
      state: started
      key_name: "{{ ssh_key_name }}"
      security_group: "{{ security_group_id }}"
      instance_type: "{{ instance_size }}"
      tags: "{{ instance_tags }}"
      image_id: "{{ ami_id }}"
      wait: true
      #wait_timeout: 120
      vpc_subnet_id: "{{ subnet_id }}"
      network:
        assign_public_ip: yes
    register: ec2_instance_facts